package chapter2;

import java.util.Scanner;

public class Exception {

	public static void main(String[] args) {
		
		// 예외 : 프로그램 실행중에 발생할 수 있는 예상치 못한 상황
		// 외부에서 데이터를 받아오거나 혹은 사용자의 조작이 포함되어있을 때 발생
		Scanner scanner = new Scanner(System.in);
		
		int number = scanner.nextInt();
		System.out.println(number);
		
		int[] numbers = new int[3];
		numbers[number] = 10;
		
		int result = 10 / number;
		
	}

}
